package Mascotas;


/**
* Mascotas/_MascotaStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Mascota.idl
* martes 13 de noviembre de 2018 13H48' COT
*/

public class _MascotaStub extends org.omg.CORBA.portable.ObjectImpl implements Mascotas.Mascota
{

  public boolean insertarMascota (int codigo, String apodo, String especie, String raza, String colorPelo, String fechaNacimiento, int numeroVacuna, String nombreVacuna)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarMascota", true);
                $out.write_long (codigo);
                $out.write_wstring (apodo);
                $out.write_wstring (especie);
                $out.write_wstring (raza);
                $out.write_wstring (colorPelo);
                $out.write_wstring (fechaNacimiento);
                $out.write_long (numeroVacuna);
                $out.write_wstring (nombreVacuna);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarMascota (codigo, apodo, especie, raza, colorPelo, fechaNacimiento, numeroVacuna, nombreVacuna        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarMascota

  public boolean actualizarMascota (int codigo, String apodo, String especie, String raza, String colorPelo, String fechaNacimiento, int numeroVacuna, String nombreVacuna)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarMascota", true);
                $out.write_long (codigo);
                $out.write_wstring (apodo);
                $out.write_wstring (especie);
                $out.write_wstring (raza);
                $out.write_wstring (colorPelo);
                $out.write_wstring (fechaNacimiento);
                $out.write_long (numeroVacuna);
                $out.write_wstring (nombreVacuna);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarMascota (codigo, apodo, especie, raza, colorPelo, fechaNacimiento, numeroVacuna, nombreVacuna        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarMascota

  public boolean eliminarMascota (int codigo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarMascota", true);
                $out.write_long (codigo);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarMascota (codigo        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarMascota

  public String consultarMascota (int codigo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarMascota", true);
                $out.write_long (codigo);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarMascota (codigo        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarMascota

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Mascotas/Mascota:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _MascotaStub
