package Mascotas;


/**
* Mascotas/Mascota.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Mascota.idl
* martes 13 de noviembre de 2018 13H48' COT
*/

public interface Mascota extends MascotaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Mascota
