package Pesos;


/**
* Pesos/PesoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peso.idl
* martes 13 de noviembre de 2018 14H41' COT
*/

public interface PesoOperations 
{
  boolean insertarPeso (int id, String apodo, String fecha, String peso);
  boolean actualizarPeso (int id, String apodo, String fecha, String peso);
  boolean eliminarPeso (int id);
  String consultarPeso (int id);
  void shutdown ();
} // interface PesoOperations
