package Pesos;

/**
* Pesos/PesoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peso.idl
* martes 13 de noviembre de 2018 14H41' COT
*/

public final class PesoHolder implements org.omg.CORBA.portable.Streamable
{
  public Pesos.Peso value = null;

  public PesoHolder ()
  {
  }

  public PesoHolder (Pesos.Peso initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Pesos.PesoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Pesos.PesoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Pesos.PesoHelper.type ();
  }

}
