package Pesos;


/**
* Pesos/Peso.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peso.idl
* martes 13 de noviembre de 2018 14H41' COT
*/

public interface Peso extends PesoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Peso
