package Pesos;


/**
* Pesos/PesoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peso.idl
* martes 13 de noviembre de 2018 14H41' COT
*/

abstract public class PesoHelper
{
  private static String  _id = "IDL:Pesos/Peso:1.0";

  public static void insert (org.omg.CORBA.Any a, Pesos.Peso that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Pesos.Peso extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Pesos.PesoHelper.id (), "Peso");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Pesos.Peso read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PesoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Pesos.Peso value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Pesos.Peso narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Pesos.Peso)
      return (Pesos.Peso)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Pesos._PesoStub stub = new Pesos._PesoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Pesos.Peso unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Pesos.Peso)
      return (Pesos.Peso)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Pesos._PesoStub stub = new Pesos._PesoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
