package Acudientes;


/**
* Acudientes/_AcudienteStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Acudiente.idl
* martes 13 de noviembre de 2018 16H11' COT
*/

public class _AcudienteStub extends org.omg.CORBA.portable.ObjectImpl implements Acudientes.Acudiente
{

  public boolean insertarAcudiente (int identificacion, String nombre, String apellido, String telefono, String direccion, String correo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarAcudiente", true);
                $out.write_long (identificacion);
                $out.write_wstring (nombre);
                $out.write_wstring (apellido);
                $out.write_wstring (telefono);
                $out.write_wstring (direccion);
                $out.write_wstring (correo);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarAcudiente (identificacion, nombre, apellido, telefono, direccion, correo        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarAcudiente

  public boolean actualizarAcudiente (int identificacion, String nombre, String apellido, String telefono, String direccion, String correo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarAcudiente", true);
                $out.write_long (identificacion);
                $out.write_wstring (nombre);
                $out.write_wstring (apellido);
                $out.write_wstring (telefono);
                $out.write_wstring (direccion);
                $out.write_wstring (correo);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarAcudiente (identificacion, nombre, apellido, telefono, direccion, correo        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarAcudiente

  public boolean eliminarAcudiente (int identificacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarAcudiente", true);
                $out.write_long (identificacion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarAcudiente (identificacion        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarAcudiente

  public String consultarAcudiente (int identificacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarAcudiente", true);
                $out.write_long (identificacion);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarAcudiente (identificacion        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarAcudiente

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Acudientes/Acudiente:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AcudienteStub
