package Acudientes;


/**
* Acudientes/AcudienteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Acudiente.idl
* martes 13 de noviembre de 2018 16H11' COT
*/

abstract public class AcudienteHelper
{
  private static String  _id = "IDL:Acudientes/Acudiente:1.0";

  public static void insert (org.omg.CORBA.Any a, Acudientes.Acudiente that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Acudientes.Acudiente extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Acudientes.AcudienteHelper.id (), "Acudiente");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Acudientes.Acudiente read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AcudienteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Acudientes.Acudiente value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Acudientes.Acudiente narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Acudientes.Acudiente)
      return (Acudientes.Acudiente)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Acudientes._AcudienteStub stub = new Acudientes._AcudienteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Acudientes.Acudiente unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Acudientes.Acudiente)
      return (Acudientes.Acudiente)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Acudientes._AcudienteStub stub = new Acudientes._AcudienteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
