package Acudientes;

/**
* Acudientes/AcudienteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Acudiente.idl
* martes 13 de noviembre de 2018 16H11' COT
*/

public final class AcudienteHolder implements org.omg.CORBA.portable.Streamable
{
  public Acudientes.Acudiente value = null;

  public AcudienteHolder ()
  {
  }

  public AcudienteHolder (Acudientes.Acudiente initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Acudientes.AcudienteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Acudientes.AcudienteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Acudientes.AcudienteHelper.type ();
  }

}
